pragma Singleton

import Quickshell
import QtQuick

Singleton {
    id: root
    enum Enum {
        DialogQuestionSymbolic,
        GoNextSymbolic,
        GoPreviousSymbolic,
        MediaSkipForwardSymbolic,
        MediaSkipBackwardSymbolic,
        MediaPlaybackStartSymbolic,
        MediaPlaybackPauseSymbolic,
        BatterySymbolic,
        BatteryLevel0ChargingSymbolic,
        BatteryLevel0PluggedInSymbolic,
        BatteryLevel0Symbolic,
        BatteryLevel10ChargingSymbolic,
        BatteryLevel10PluggedInSymbolic,
        BatteryLevel10Symbolic,
        BatteryLevel20ChargingSymbolic,
        BatteryLevel20PluggedInSymbolic,
        BatteryLevel20Symbolic,
        BatteryLevel30ChargingSymbolic,
        BatteryLevel30PluggedInSymbolic,
        BatteryLevel30Symbolic,
        BatteryLevel40ChargingSymbolic,
        BatteryLevel40PluggedInSymbolic,
        BatteryLevel40Symbolic,
        BatteryLevel50ChargingSymbolic,
        BatteryLevel50PluggedInSymbolic,
        BatteryLevel50Symbolic,
        BatteryLevel60ChargingSymbolic,
        BatteryLevel60PluggedInSymbolic,
        BatteryLevel60Symbolic,
        BatteryLevel70ChargingSymbolic,
        BatteryLevel70PluggedInSymbolic,
        BatteryLevel70Symbolic,
        BatteryLevel80ChargingSymbolic,
        BatteryLevel80PluggedInSymbolic,
        BatteryLevel80Symbolic,
        BatteryLevel90ChargingSymbolic,
        BatteryLevel90PluggedInSymbolic,
        BatteryLevel90Symbolic,
        BatteryLevel100ChargedSymbolic,
        BatteryLevel100PluggedInSymbolic,
        BatteryLevel100Symbolic,
        BatteryMissingSymbolic,
        AudioVolumeHighSymbolic,
        AudioVolumeLowSymbolic,
        AudioVolumeMediumSymbolic,
        AudioVolumeMutedSymbolic,
        AudioVolumeOveramplifiedSymbolic,
        AudioHeadphonesSymbolic,
        AudioInputMicrophoneSymbolic,
        OpenMenuSymbolic,
        SystemLockScreenSymbolic,
        SystemRebootSymbolic,
        SystemShutdownSymbolic,
        ApplicationExitSymbolic,
        AvatarDefaultSymbolic,
        BluetoothSymbolic,
        BluetoothDisabledSymbolic
    }

    readonly property var map: ({
            [Icons.DialogQuestionSymbolic]: "dialog-question-symbolic",
            [Icons.GoNextSymbolic]: "go-next-symbolic",
            [Icons.GoPreviousSymbolic]: "go-previous-symbolic",
            [Icons.MediaSkipForwardSymbolic]: "media-skip-forward-symbolic",
            [Icons.MediaSkipBackwardSymbolic]: "media-skip-backward-symbolic",
            [Icons.MediaPlaybackStartSymbolic]: "media-playback-start-symbolic",
            [Icons.MediaPlaybackPauseSymbolic]: "media-playback-pause-symbolic",
            [Icons.BatterySymbolic]: "battery-symbolic",
            [Icons.BatteryLevel0ChargingSymbolic]: "battery-level-0-charging-symbolic",
            [Icons.BatteryLevel0PluggedInSymbolic]: "battery-level-0-plugged-in-symbolic",
            [Icons.BatteryLevel0Symbolic]: "battery-level-0-symbolic",
            [Icons.BatteryLevel10ChargingSymbolic]: "battery-level-10-charging-symbolic",
            [Icons.BatteryLevel10PluggedInSymbolic]: "battery-level-10-plugged-in-symbolic",
            [Icons.BatteryLevel10Symbolic]: "battery-level-10-symbolic",
            [Icons.BatteryLevel20ChargingSymbolic]: "battery-level-20-charging-symbolic",
            [Icons.BatteryLevel20PluggedInSymbolic]: "battery-level-20-plugged-in-symbolic",
            [Icons.BatteryLevel20Symbolic]: "battery-level-20-symbolic",
            [Icons.BatteryLevel30ChargingSymbolic]: "battery-level-30-charging-symbolic",
            [Icons.BatteryLevel30PluggedInSymbolic]: "battery-level-30-plugged-in-symbolic",
            [Icons.BatteryLevel30Symbolic]: "battery-level-30-symbolic",
            [Icons.BatteryLevel40ChargingSymbolic]: "battery-level-40-charging-symbolic",
            [Icons.BatteryLevel40PluggedInSymbolic]: "battery-level-40-plugged-in-symbolic",
            [Icons.BatteryLevel40Symbolic]: "battery-level-40-symbolic",
            [Icons.BatteryLevel50ChargingSymbolic]: "battery-level-50-charging-symbolic",
            [Icons.BatteryLevel50PluggedInSymbolic]: "battery-level-50-plugged-in-symbolic",
            [Icons.BatteryLevel50Symbolic]: "battery-level-50-symbolic",
            [Icons.BatteryLevel60ChargingSymbolic]: "battery-level-60-charging-symbolic",
            [Icons.BatteryLevel60PluggedInSymbolic]: "battery-level-60-plugged-in-symbolic",
            [Icons.BatteryLevel60Symbolic]: "battery-level-60-symbolic",
            [Icons.BatteryLevel70ChargingSymbolic]: "battery-level-70-charging-symbolic",
            [Icons.BatteryLevel70PluggedInSymbolic]: "battery-level-70-plugged-in-symbolic",
            [Icons.BatteryLevel70Symbolic]: "battery-level-70-symbolic",
            [Icons.BatteryLevel80ChargingSymbolic]: "battery-level-80-charging-symbolic",
            [Icons.BatteryLevel80PluggedInSymbolic]: "battery-level-80-plugged-in-symbolic",
            [Icons.BatteryLevel80Symbolic]: "battery-level-80-symbolic",
            [Icons.BatteryLevel90ChargingSymbolic]: "battery-level-90-charging-symbolic",
            [Icons.BatteryLevel90PluggedInSymbolic]: "battery-level-90-plugged-in-symbolic",
            [Icons.BatteryLevel90Symbolic]: "battery-level-90-symbolic",
            [Icons.BatteryLevel100ChargedSymbolic]: "battery-level-100-charged-symbolic",
            [Icons.BatteryLevel100PluggedInSymbolic]: "battery-level-100-plugged-in-symbolic",
            [Icons.BatteryLevel100Symbolic]: "battery-level-100-symbolic",
            [Icons.BatteryMissingSymbolic]: "battery-missing-symbolic",
            [Icons.AudioVolumeHighSymbolic]: "audio-volume-high-symbolic",
            [Icons.AudioVolumeLowSymbolic]: "audio-volume-low-symbolic",
            [Icons.AudioVolumeMediumSymbolic]: "audio-volume-medium-symbolic",
            [Icons.AudioVolumeMutedSymbolic]: "audio-volume-muted-symbolic",
            [Icons.AudioVolumeOveramplifiedSymbolic]: "audio-volume-overamplified-symbolic",
            [Icons.AudioHeadphonesSymbolic]: "audio-headphones-symbolic",
            [Icons.AudioInputMicrophoneSymbolic]: "audio-input-microphone-symbolic",
            [Icons.OpenMenuSymbolic]: "open-menu-symbolic",
            [Icons.SystemLockScreenSymbolic]: "system-lock-screen-symbolic",
            [Icons.SystemRebootSymbolic]: "system-reboot-symbolic",
            [Icons.SystemShutdownSymbolic]: "system-shutdown-symbolic",
            [Icons.ApplicationExitSymbolic]: "application-exit-symbolic",
            [Icons.AvatarDefaultSymbolic]: "avatar-default-symbolic",
            [Icons.BluetoothSymbolic]: "bluetooth-symbolic",
            [Icons.BluetoothDisabledSymbolic]: "bluetooth-disabled-symbolic"
        })

    function get(icon: int): string {
        // return Quickshell.iconPath(Qt.enumValueToString(Icons.Enum, icon).replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase());
        return Quickshell.iconPath(root.map[icon]);
    }

    function getString(icon: int): string {
        return root.map[icon];
    }
}
