pragma Singleton

import Quickshell
import QtQuick

Singleton {
    id: root
    enum Enum {
        GoNextSymbolic,
        GoPreviousSymbolic,
        MediaSkipForwardSymbolic,
        MediaSkipBackwardSymbolic,
        MediaPlaybackStartSymbolic,
        MediaPlaybackPauseSymbolic,
        BatteryLevel0ChargingSymbolic,
        BatteryLevel0PluggedInSymbolic,
        BatteryLevel0Symbolic,
        BatteryLevel10ChargingSymbolic,
        BatteryLevel10PluggedInSymbolic,
        BatteryLevel10Symbolic,
        BatteryLevel20ChargingSymbolic,
        BatteryLevel20PluggedInSymbolic,
        BatteryLevel20Symbolic,
        BatteryLevel30ChargingSymbolic,
        BatteryLevel30PluggedInSymbolic,
        BatteryLevel30Symbolic,
        BatteryLevel40ChargingSymbolic,
        BatteryLevel40PluggedInSymbolic,
        BatteryLevel40Symbolic,
        BatteryLevel50ChargingSymbolic,
        BatteryLevel50PluggedInSymbolic,
        BatteryLevel50Symbolic,
        BatteryLevel60ChargingSymbolic,
        BatteryLevel60PluggedInSymbolic,
        BatteryLevel60Symbolic,
        BatteryLevel70ChargingSymbolic,
        BatteryLevel70PluggedInSymbolic,
        BatteryLevel70Symbolic,
        BatteryLevel80ChargingSymbolic,
        BatteryLevel80PluggedInSymbolic,
        BatteryLevel80Symbolic,
        BatteryLevel90ChargingSymbolic,
        BatteryLevel90PluggedInSymbolic,
        BatteryLevel90Symbolic,
        BatteryLevel100ChargedSymbolic,
        BatteryLevel100PluggedInSymbolic,
        BatteryLevel100Symbolic,
        BatteryMissingSymbolic,
        AudioVolumeHighSymbolic,
        AudioVolumeLowSymbolic,
        AudioVolumeMediumSymbolic,
        AudioVolumeMutedSymbolic,
        AudioVolumeOveramplifiedSymbolic,
        OpenMenuSymbolic,
        SystemLockScreenSymbolic,
        SystemRebootSymbolic,
        SystemShutdownSymbolic,
        ApplicationExitSymbolic,
        AvatarDefaultSymbolic
    }

    readonly property var map: ({
            [Icons.GoNextSymbolic]: "go-next-symbolic",
            [Icons.GoPreviousSymbolic]: "go-previous-symbolic",
            [Icons.MediaSkipForwardSymbolic]: "media-skip-forward-symbolic",
            [Icons.MediaSkipBackwardSymbolic]: "media-skip-backward-symbolic",
            [Icons.MediaPlaybackStartSymbolic]: "media-playback-start-symbolic",
            [Icons.MediaPlaybackPauseSymbolic]: "media-playback-pause-symbolic",
            [Icons.BatteryLevel0ChargingSymbolic]: "battery-level0-charging-symbolic",
            [Icons.BatteryLevel0PluggedInSymbolic]: "battery-level0-plugged-in-symbolic",
            [Icons.BatteryLevel0Symbolic]: "battery-level0-symbolic",
            [Icons.BatteryLevel10ChargingSymbolic]: "battery-level10-charging-symbolic",
            [Icons.BatteryLevel10PluggedInSymbolic]: "battery-level10-plugged-in-symbolic",
            [Icons.BatteryLevel10Symbolic]: "battery-level10-symbolic",
            [Icons.BatteryLevel20ChargingSymbolic]: "battery-level20-charging-symbolic",
            [Icons.BatteryLevel20PluggedInSymbolic]: "battery-level20-plugged-in-symbolic",
            [Icons.BatteryLevel20Symbolic]: "battery-level20-symbolic",
            [Icons.BatteryLevel30ChargingSymbolic]: "battery-level30-charging-symbolic",
            [Icons.BatteryLevel30PluggedInSymbolic]: "battery-level30-plugged-in-symbolic",
            [Icons.BatteryLevel30Symbolic]: "battery-level30-symbolic",
            [Icons.BatteryLevel40ChargingSymbolic]: "battery-level40-charging-symbolic",
            [Icons.BatteryLevel40PluggedInSymbolic]: "battery-level40-plugged-in-symbolic",
            [Icons.BatteryLevel40Symbolic]: "battery-level40-symbolic",
            [Icons.BatteryLevel50ChargingSymbolic]: "battery-level50-charging-symbolic",
            [Icons.BatteryLevel50PluggedInSymbolic]: "battery-level50-plugged-in-symbolic",
            [Icons.BatteryLevel50Symbolic]: "battery-level50-symbolic",
            [Icons.BatteryLevel60ChargingSymbolic]: "battery-level60-charging-symbolic",
            [Icons.BatteryLevel60PluggedInSymbolic]: "battery-level60-plugged-in-symbolic",
            [Icons.BatteryLevel60Symbolic]: "battery-level60-symbolic",
            [Icons.BatteryLevel70ChargingSymbolic]: "battery-level70-charging-symbolic",
            [Icons.BatteryLevel70PluggedInSymbolic]: "battery-level70-plugged-in-symbolic",
            [Icons.BatteryLevel70Symbolic]: "battery-level70-symbolic",
            [Icons.BatteryLevel80ChargingSymbolic]: "battery-level80-charging-symbolic",
            [Icons.BatteryLevel80PluggedInSymbolic]: "battery-level80-plugged-in-symbolic",
            [Icons.BatteryLevel80Symbolic]: "battery-level80-symbolic",
            [Icons.BatteryLevel90ChargingSymbolic]: "battery-level90-charging-symbolic",
            [Icons.BatteryLevel90PluggedInSymbolic]: "battery-level90-plugged-in-symbolic",
            [Icons.BatteryLevel90Symbolic]: "battery-level90-symbolic",
            [Icons.BatteryLevel100ChargedSymbolic]: "battery-level100-charged-symbolic",
            [Icons.BatteryLevel100PluggedInSymbolic]: "battery-level100-plugged-in-symbolic",
            [Icons.BatteryLevel100Symbolic]: "battery-level100-symbolic",
            [Icons.BatteryMissingSymbolic]: "battery-missing-symbolic",
            [Icons.AudioVolumeHighSymbolic]: "audio-volume-high-symbolic",
            [Icons.AudioVolumeLowSymbolic]: "audio-volume-low-symbolic",
            [Icons.AudioVolumeMediumSymbolic]: "audio-volume-medium-symbolic",
            [Icons.AudioVolumeMutedSymbolic]: "audio-volume-muted-symbolic",
            [Icons.AudioVolumeOveramplifiedSymbolic]: "audio-volume-overamplified-symbolic",
            [Icons.OpenMenuSymbolic]: "open-menu-symbolic",
            [Icons.SystemLockScreenSymbolic]: "system-lock-screen-symbolic",
            [Icons.SystemRebootSymbolic]: "system-reboot-symbolic",
            [Icons.SystemShutdownSymbolic]: "system-shutdown-symbolic",
            [Icons.ApplicationExitSymbolic]: "application-exit-symbolic",
            [Icons.AvatarDefaultSymbolic]: "avatar-default-symbolic"
        })

    function get(icon: int): string {
        // return Quickshell.iconPath(Qt.enumValueToString(Icons.Enum, icon).replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase());
        return Quickshell.iconPath(root.map[icon]);
    }
}
