# Monitors
monitor = , preferred, auto, 1

dwindle {
    preserve_split = true 
    force_split = 2
}

$dotfiles_path = /home/bolt/.local/share/dotfiles
source = $dotfiles_path/config/hypr/modules/*
source = $dotfiles_path/config/hypr/modules/rules/*
source = $dotfiles_path/local/hypr.conf


