$terminal = alacritty
$fileManager = nautilus
$menu = wofi
$browser = firefox
$notificationd = mako
$clipboardmanager = cliphist
$mount = udiskie
$dotfiles_path = /home/bolt/.local/share/dotfiles

monitor = , preferred, auto, 1

dwindle {
    preserve_split = true 
    force_split = 2
}

source = $dotfiles_path/themes/current/hypr.conf
source = $dotfiles_path/config/hypr/modules/*
source = $dotfiles_path/config/hypr/modules/rules/*
source = $dotfiles_path/local/hypr.conf

exec-once = uwsm app -- wl-paste --type text --watch $clipboardmanager store
exec-once = uwsm app -- wl-paste --type image --watch $clipboardmanager store
exec-once = uwsm app -- $mount -a -n -t
exec-once = uwsm app -- qs
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP


