# cliphist
exec-once = uwsm app -- wl-paste --type text --watch $clipboardmanager store
exec-once = uwsm app -- wl-paste --type image --watch $clipboardmanager store
# automatic mount
exec-once = uwsm app -- $mount -a -n -t
# start shell
exec-once = qs
