general {
    layout = dwindle
    border_size = 2
    gaps_in = 4
    gaps_out = 8
    col.inactive_border = $background
    col.active_border = $main
    col.nogroup_border = $warning
    col.nogroup_border_active = $second
    allow_tearing = true
}
